version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: edgar_mysql
    restart: always
    build: 'docker/mysql/'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
    # volumes:
    #   - .docker/mysql/scripts/:/docker-entrypoint-initdb.d/


